config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'sessions#new'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :tasks

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks
  validates :description, presence: true, length: {minimum: 3, maximum: 100}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user

  validates :description, presence: true, length: {minimum: 5, maximum: 100}
  validates :date_task, presence: true
  validates :category, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :categories
    has_many :tasks
    before_save { self.email = email.downcase }
    validates :username, presence: true,
            uniqueness: { case_sensitive: false},
            length: {minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            redirect_to root_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  def new
    @category = Category.new
  end

  def create
    # render plain: params[:category].inspect
    @category = Category.new(category_params)
    @category.user = current_user
    if @category.save
      flash[:notice] ="Category sucessfullly added"
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] ="Category sucessfullly edited"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category Successfully deleted"
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to user_path(@current_user) if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in"
      redirect_to user_path(user)
    else
        flash.now[:danger] = "Email and password didn't matched"
        render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    render 'new'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, except: [:new, :create ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Account successfully created"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Account successfully updated"
      redirect_to categories_path
    else
      render 'edit'
    end
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<% @category.errors.any? %>
<ul>
  <% @category.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<%= form_with model: @category do |form| %>
  <%= form.label :description %><br/>
  <%= form.text_field :description %><br/>
  <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<% @categories.each do |category| %>
  <ul>
    <li><%= category.description %></li>
    <li><%= link_to "Delete", category_path(category), method: :delete, data: {confirm: "delete category?"} %></li>
    <li><%= link_to "Show",category_path(category) %> </li>
    <li><%= link_to "Edit",edit_category_path(category) %> </li>
  </ul>
<% end %>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Selected Category</h1>
<h2><%= @category.description %></h2>
<p>list of tasks goes here </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalAppAlpha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
      <% end %>
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/tasks/new.html.erb
<div class="w-full">

<% @task.errors.any? %>
<ul>
  <% @task.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
  <div class="h-2 bg-indigo" ></div>
    <div class="bg-cover flex items-center justify-center h-screen" style="background-image: url('https://images.unsplash.com/photo-1592474096967-7e5d62070cf7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80')">
      <div class="container mx-24 bg-white rounded shadow-lg">
        <div class="px-12 py-6">
          <div class="text-center">
            <h1 class="font-normal text-3xl text-grey-darkest leading-loose my-3 w-full">Add Task</h1>
            <div class="w-full text-center">
            <%= form_with model: @category do |form| %>
              
                <div class="max-w-sm mx-auto p-1 pr-0 flex-column items-center">
                 <%= form.text_field :description, placeholder:"Ex. Groceries", class:"flex-1 appearance-none rounded shadow p-3 text-grey-dark mr-2 focus:outline-none" %>
                 <%= form.text_field :task_date, placeholder:"Format: DD-MM-YYYY", class:"flex-1 appearance-none rounded shadow p-3 text-grey-dark mr-2 focus:outline-none" %></br>
                 <%= form.submit 'Create', class: "appearance-none bg-blue-700 text-white text-base font-semibold tracking-wide uppercase p-3 rounded shadow hover:bg-blue-900" %> 
                </div>
              
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/users/_form.html.erb
<% @user.errors.any? %>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<div class="w-full flex flex-wrap">

<!-- Login Section -->
<div class="w-full md:w-1/2 flex flex-col">

    <div class="flex justify-center md:justify-start pt-12 md:pl-12 md:-mb-24">
        <a href="#" class="bg-black text-white font-bold text-xl p-4">Journal App</a>
    </div>

    <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
        <p class="text-center text-3xl">Welcome.</p>
        <%= form_with model: @user, class: "flex flex-col pt-3 md:pt-8"  do |form| %>
        
            <div class="flex flex-col pt-4">
              <%= form.label :first_name, class: "text-lg"%><br/>
              <%= form.text_field :first_name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Enter your email" %><br/>
               
            </div>

            <div class="flex flex-col pt-4">
              <%= form.label :last_name, class: "text-lg"%><br/>
              <%= form.text_field :last_name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline", placeholder:"Password" %><br/>
             </div>

             <div class="flex flex-col pt-4">
             <%= form.label :username, class: "text-lg"%><br/>
             <%= form.text_field :username, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Enter your email" %><br/>
              
           </div>

           <div class="flex flex-col pt-4">
           <%= form.label :email, class: "text-lg"%><br/>
           <%= form.email_field :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Enter your email" %><br/>
            
         </div>

         <div class="flex flex-col pt-4">
         <%= form.label :password, class: "text-lg"%><br/>
         <%= form.password_field :password, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Enter your email" %><br/>
          
       </div>
       <%= form.submit(@user.new_record? ? "Sign Up" : "Update", class: "bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8") %>
        <% end %>
  
    </div>

</div>

<!-- Image Section -->
<div class="w-1/2 shadow-2xl">
    <img class="object-cover w-full h-screen hidden md:block" src="https://images.unsplash.com/photo-1592474096967-7e5d62070cf7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80">
</div>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<!-- component -->
<link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
<link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">

<main class="profile-page">
  <section class="relative block h-500-px">
    <div class="absolute top-0 w-full h-full bg-center bg-cover" style="
            background-image: url('https://images.unsplash.com/photo-1499336315816-097655dcfbda?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=2710&amp;q=80');
          ">
      <span id="blackOverlay" class="w-full h-full absolute opacity-50 bg-black"></span>
    </div>
    <div class="top-auto bottom-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden h-70-px" style="transform: translateZ(0px)">
      <svg class="absolute bottom-0 overflow-hidden" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" version="1.1" viewBox="0 0 2560 100" x="0" y="0">
        <polygon class="text-blueGray-200 fill-current" points="2560 0 2560 100 0 100"></polygon>
      </svg>
    </div>
  </section>
  <section class="relative py-16 bg-blueGray-200">
    <div class="container mx-auto px-4">
      <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64">
        <div class="px-6">
          <div class="flex flex-wrap justify-center">
            <div class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center">
              <div class="relative">
                <img alt="..." src="https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg" class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16 max-w-150-px">
              </div>
            </div>
            <div class="w-full lg:w-4/12 px-4 lg:order-3 lg:text-right lg:self-center">
              <div class="py-6 px-3 mt-32 sm:mt-0">
              <div><%= link_to 'Log Out', logout_path, method: :delete, class: "bg-black active:bg-black uppercase text-white font-bold hover:shadow-md shadow text-xs px-4 py-2 rounded outline-none focus:outline-none sm:mr-2 mb-1 ease-linear transition-all duration-150" %></div>
              </div>
            </div>
            <div class="w-full lg:w-4/12 px-4 lg:order-1">
              <div class="flex justify-center py-4 lg:pt-4 pt-8">
                <div class="mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">22</span><span class="text-sm text-blueGray-400">Friends</span>
                </div>
                <div class="mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">10</span><span class="text-sm text-blueGray-400">Photos</span>
                </div>
                <div class="lg:mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">89</span><span class="text-sm text-blueGray-400">Comments</span>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center mt-12">
            <h3 class="text-4xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2">
             <%= @user.first_name %> <%= @user.last_name %>
            </h3>
            <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
              <i class="fas fa-map-marker-alt mr-2 text-lg text-blueGray-400"></i>
              Los Angeles, California
            </div>
            <div class="mb-2 text-blueGray-600 mt-10">
              <i class="fas fa-briefcase mr-2 text-lg text-blueGray-400"></i>Solution Manager - Creative Tim Officer
            </div>
            <div class="mb-2 text-blueGray-600">
              <i class="fas fa-university mr-2 text-lg text-blueGray-400"></i>University of Computer Science
            </div>
          </div>
          <div class="mt-10 py-10 border-t border-blueGray-200 text-center">
            <div class="flex flex-wrap justify-center">
              <div class="w-full lg:w-9/12 px-4">
                <p class="mb-4 text-lg leading-relaxed text-blueGray-700">
                <% @user.categories.each do |category| %>
                    <ul>
                      <li><%= category.description %></li>
                      <li><%= link_to 'show', category_path(category) %></li>
                    </ul>
                <% end %>
                </p>
                <a href="#pablo" class="font-normal text-pink-500">Show more</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer class="relative bg-blueGray-200 pt-8 pb-6 mt-8">
  <div class="container mx-auto px-4">
    <div class="flex flex-wrap items-center md:justify-between justify-center">
      <div class="w-full md:w-6/12 px-4 mx-auto text-center">
        <div class="text-sm text-blueGray-500 font-semibold py-1">
          Made with <a href="https://www.creative-tim.com/product/notus-js" class="text-blueGray-500 hover:text-gray-800" target="_blank">Notus JS</a> by <a href="https://www.creative-tim.com" class="text-blueGray-500 hover:text-blueGray-800" target="_blank"> Creative Tim</a>.
        </div>
      </div>
    </div>
  </div>
</footer>
  </section>
</main>